# Generated by Django 4.2.1 on 2025-04-06 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_comment_likedreply_tag_alter_post_date_posted_reply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likedpost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likedreply',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='likedreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parent_comment',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='parent_post',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='LikedComment',
        ),
        migrations.DeleteModel(
            name='LikedPost',
        ),
        migrations.DeleteModel(
            name='LikedReply',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
