# Generated by Django 4.2.1 on 2025-04-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_likedpost_post_remove_likedpost_user_and_more'),
    ]

    operations = [
    ]
